src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_categorie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="text")
     */
    private $texte;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $visuel;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneCommande", mappedBy="id_article")
     */
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdCategorie(): ?Categorie
    {
        return $this->id_categorie;
    }

    public function setIdCategorie(?Categorie $id_categorie): self
    {
        $this->id_categorie = $id_categorie;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(string $texte): self
    {
        $this->texte = $texte;

        return $this;
    }

    public function getVisuel(): ?string
    {
        return $this->visuel;
    }

    public function setVisuel(string $visuel): self
    {
        $this->visuel = $visuel;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setIdArticle($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes->removeElement($ligneCommande);
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getIdArticle() === $this) {
                $ligneCommande->setIdArticle(null);
            }
        }

        return $this;
    }
}

src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usager", inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_usager;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_commande;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\LigneCommande", mappedBy="id_commande")
     */
    private $ligneCommandes;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUsager(): ?Usager
    {
        return $this->id_usager;
    }

    public function setIdUsager(?Usager $id_usager): self
    {
        $this->id_usager = $id_usager;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setIdCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes->removeElement($ligneCommande);
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getIdCommande() === $this) {
                $ligneCommande->setIdCommande(null);
            }
        }

        return $this;
    }
}

templates/backoffice.html.twig
{# templates/backoffice.html.twig #}
{% extends 'base.html.twig' %}
{% block content %}
<div class="site-section mt-5">

<div class="container">
        <div class="row">
            <div class="col-lg-6 mb-6 col-md-6">
                <a class="btn btn-primary btn-lg btn-block" href="{{ path('article_index') }}">CRUD Article</a>
            </div>
            <div class="col-lg-6 mb-6 col-md-6">
                <a class="btn btn-primary btn-lg btn-block" href="{{ path('categorie_index') }}">CRUD Categorie</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html.twig
{# templates/base.html.twig #}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        {% block style %}{% endblock %}
        <link href="https://fonts.googleapis.com/css?family=Cinzel:400,700|Montserrat:400,700|Roboto&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ asset('fonts/icomoon/style.css') }}">
        <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/jquery-ui.css') }}">
        <link rel="stylesheet" href="{{ asset('css/owl.carousel.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/owl.theme.default.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/owl.theme.default.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/jquery.fancybox.min.css') }}">
        <link rel="stylesheet" href="{{ asset('css/bootstrap-datepicker.css') }}">
        <link rel="stylesheet" href="{{ asset('fonts/flaticon/font/flaticon.css') }}">
        <link rel="stylesheet" href="{{ asset('css/aos.css') }}">
        <link href="{{ asset('css/jquery.mb.YTPlayer.min.css') }}" media="all" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    </head>
    <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
        {% include 'header.html.twig' %}
        {% block content %} {% endblock %}
        {% include 'footer.html.twig' %}
        {% include 'script.html.twig' %}
        {% block script %}{% endblock %}
    </body>
</html>

templates/contact.html.twig
{# templates/shop.html.twig #}
{% extends 'base.html.twig' %}
{% block content %}

    <div class="site-wrap">

        <div class="hero-2" style="background-image: url({{ asset('images/hero_2.jpg') }});">
            <div class="container">
                <div class="row justify-content-center text-center align-items-center">
                    <div class="col-md-8">
                        <span class="sub-title">Get In Touch</span>
                        <h2>Contact</h2>
                    </div>
                </div>
            </div>
        </div>


        <div class="site-section bg-light">
            <div class="container">
                <div class="row">

                    <div class="col-lg-12">
                        <div class="section-title mb-5">
                            <h2>Contact Us</h2>
                        </div>
                        <form method="post">

                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label for="fname">First Name</label>
                                    <input type="text" id="fname" class="form-control form-control-lg">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="lname">Last Name</label>
                                    <input type="text" id="lname" class="form-control form-control-lg">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label for="eaddress">Email Address</label>
                                    <input type="text" id="eaddress" class="form-control form-control-lg">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label for="tel">Tel. Number</label>
                                    <input type="text" id="tel" class="form-control form-control-lg">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <label for="message">Message</label>
                                    <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                                </div>
                            </div>

                        </form>
                    </div>

                </div>


            </div>
        </div>
{% endblock %}

templates/footer.html.twig
{# templates/footer.html.twig #}
<div class="footer">
    <div class="container">

        <div class="row">
            <div class="col-12 text-center">
                <div class="social-icons">
                    <a href="#"><span class="icon-facebook"></span></a>
                    <a href="#"><span class="icon-twitter"></span></a>
                    <a href="#"><span class="icon-youtube"></span></a>
                    <a href="#"><span class="icon-instagram"></span></a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="copyright">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>



                </div>
            </div>
        </div>
    </div>
</div>

templates/header.html.twig
{# templates/header.html.twig #}
<div class="header-top">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 text-center">
                <a href="{{ path('home_page') }}" class="site-logo">
                    <img src="{{ asset('images/logo.png') }}" alt="Image" class="img-fluid">
                </a>
            </div>
            <a href="#" class="mx-auto d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black"><span
                        class="icon-menu h3"></span></a>
        </div>
    </div>




    <div class="site-navbar py-2 js-sticky-header site-navbar-target d-none pl-0 d-lg-block" role="banner">

        <div class="container">
            <div class="d-flex align-items-center">

                <div class="mx-auto">
                    <nav class="site-navigation position-relative text-left" role="navigation">
                        <ul class="site-menu main-menu js-clone-nav mx-auto d-none pl-0 d-lg-block border-none">
                            <li><a href="{{ path('home_page') }}" class="nav-link text-left">{{ 'home' | trans }}</a></li>
                            <li><a href="{{ path('wines_page', { '_locale' : 'fr'}) }}" class="nav-link text-left">{{ 'wines' | trans }}</a></li>
                            {% if app.user %}
                                <li><a href="{{ path('usager_accueil', { '_locale' : 'fr'}) }}" class="nav-link text-left">Mon compte</a></li>
                            {% else %}
                                <li><a href="{{ path('usager_inscription', { '_locale' : 'fr'}) }}" class="nav-link text-left">Inscription</a></li>
                                <li><a href="{{ path('app_login') }}" class="nav-link text-left">Connexion</a></li>
                            {% endif %}
                            {% if is_granted('ROLE_ADMIN') %}
                                <li><a href="{{ path('backoffice_admin') }}" class="nav-link text-left">Backoffice</a></li>
                            {% endif %}
                        </ul>
                    </nav>

                </div>

            </div>
        </div>

    </div>

</div>

templates/panier.html.twig
{# templates/single.html.twig #}
{% extends 'base.html.twig' %}
{% block content %}
    <div class="site-section  pb-0">
        <div class="container">
            <div class="row mb-5 justify-content-center">
                <div class="col-7 section-title text-center mb-5">
                    <h2 class="d-block">Cart</h2>
                </div>
            </div>
            <div class="row mb-5">
                <form class="col-md-12" method="post">
                    <div class="site-blocks-table">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th class="product-thumbnail">Image</th>
                                <th class="product-name">Product</th>
                                <th class="product-price">Price</th>
                                <th class="product-quantity">Quantity</th>
                                <th class="product-total">Total</th>
                                <th class="product-remove">Remove</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in contenu %}

                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{ asset('images/wine_'~item.produit.idCategorie~'.png') }}" alt="Image" class="img-fluid">
                                </td>
                                <td class="product-name">
                                    <h2 class="h5 cart-product-title text-black">{{ item.produit.libelle }}</h2>
                                </td>
                                <td>{{ item.produit.prix }}€</td>
                                <td>
                                    <div class="input-group mb-3" style="max-width:180px;">
                                        <div class="input-group-prepend">
                                            <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
                                        </div>
                                        <input type="text" class="form-control text-center border mr-0" value="{{ item.quantite }}" placeholder=""
                                               aria-label="Example text with button addon" aria-describedby="button-addon1">
                                        <div class="input-group-append">
                                            <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                                        </div>
                                    </div>

                                </td>
                                <td>{{ item.produit.prix * item .quantite }}€</td>
                                <td><a href="{{ path('panier_supprimer', { '_locale' : 'fr', 'idProduit' : item.produit.id}) }}" class="btn btn-primary height-auto btn-sm">X</a></td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </form>
            </div>

        </div>
    </div>

    <div class="site-section pt-5 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="row mb-5">
                        <div class="col-md-6 mb-3 mb-md-0">
                            <button class="btn btn-primary btn-md btn-block">Update Cart</button>
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-outline-primary btn-md btn-block">Continue Shopping</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label class="text-black h4" for="coupon">Coupon</label>
                            <p>Enter your coupon code if you have one.</p>
                        </div>
                        <div class="col-md-8 mb-3 mb-md-0">
                            <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-primary btn-md px-4">Apply Coupon</button>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 pl-5">
                    <div class="row justify-content-end">
                        <div class="col-md-7">
                            <div class="row">
                                <div class="col-md-12 text-right border-bottom mb-5">
                                    <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span class="text-black">Subtotal</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">{{ total }}€</strong>
                                </div>
                            </div>
                            <div class="row mb-5">
                                <div class="col-md-6">
                                    <span class="text-black">Total</span>
                                </div>
                                <div class="col-md-6 text-right">
                                    <strong class="text-black">{{ total }}€</strong>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <a href="{{ path('panier_validation', { '_locale' : 'fr' }) }}" class="btn btn-primary btn-lg btn-block">Valider la commande</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/panier_validation.html.twig
{# templates/panier_validation.html.twig #}
{% extends 'base.html.twig' %}
{% block content %}
    <h2>Votre commande a bien été passée</h2>
    <p>Commandé le {{ commande.dateCommande|date('Y-m-d') }}</p>
    <p>Numéro de commande : {{ commande.id }}</p>
{% endblock %}

templates/product.html.twig
{# templates/product.html.twig #}
{% extends 'base.html.twig' %}
{% block content %}
    <div class="site-section mt-5">
    <div class="container">
        <div class="row">
            {% for item in wines %}
                <div class="col-lg-4 mb-5 col-md-6">

                    <div class="wine_v_1 text-center pb-4">
                        <a href="{{ path('single_page', { '_locale' : 'fr', 'categorie' : categorie, 'product' : item.id}) }}" class="thumbnail d-block mb-4"><img src="{{ asset('images/wine_'~categorie~'.png') }}" alt="Image" class="img-fluid"></a>
                        <div>
                            <h3 class="heading mb-1"><a href="#">{{ item.libelle }}</a></h3>
                            <span class="price">{{ item.prix }}€</span>
                        </div>


                        <div class="wine-actions">

                            <h3 class="heading-2"><a href="#">{{ item.libelle }}</a></h3>
                            <span class="price d-block">{{ item.prix }}€</span>

                            <div class="rating">
                                <span class="icon-star"></span>
                                <span class="icon-star"></span>
                                <span class="icon-star"></span>
                                <span class="icon-star"></span>
                                <span class="icon-star-o"></span>
                            </div>

                            <a href="{{ path('panier_ajouter', { '_locale' : 'fr', 'idProduit' : item.id, 'quantite' : 1}) }}" class="btn add"><span class="icon-shopping-bag mr-3"></span>{{ 'addCart' | trans }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

templates/script.html.twig
{# templates/script.html.twig #}
<script src={{ asset('js/jquery-3.3.1.min.js') }}></script>
<script src={{ asset('js/jquery-migrate-3.0.1.min.js') }}></script>
<script src={{ asset('js/jquery-ui.js') }}></script>
<script src={{ asset('js/popper.min.js') }}></script>
<script src={{ asset('js/bootstrap.min.js') }}></script>
<script src={{ asset('js/owl.carousel.min.js') }}></script>
<script src={{ asset('js/jquery.stellar.min.js') }}></script>
<script src={{ asset('js/jquery.countdown.min.js') }}></script>
<script src={{ asset('js/bootstrap-datepicker.min.js') }}></script>
<script src={{ asset('js/jquery.easing.1.3.js') }}></script>
<script src={{ asset('js/aos.js') }}></script>
<script src={{ asset('js/jquery.fancybox.min.js') }}></script>
<script src={{ asset('js/jquery.sticky.js') }}></script>
<script src={{ asset('js/jquery.mb.YTPlayer.min.js') }}></script>
<script src={{ asset('js/main.js') }}></script>

templates/single.html.twig
{# templates/single.html.twig #}
{% extends 'base.html.twig' %}
{% block content %}
    <div class="site-section bg-primary py-5 page-title-wrap mt-5">
        <div class="container">
            <h1>{{ single.libelle }}</h1>
        </div>
    </div>




    <div class="site-section mt-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="owl-carousel hero-slide owl-style">
                        <img src="{{ asset('images/wine_'~categorie~'.png') }}" alt="Image" class="img-fluid">
                    </div>
                </div>
                <div class="col-lg-5 ml-auto">
                    <h2 class="text-primary">Wine Details</h2>
                    <p>{{ single.texte }}</p>

                    <div class="mb-5">
                        <div class="input-group mb-3" style="max-width: 200px;">
                            <div class="input-group-prepend">
                                <button id="btnQuantiteMinus" class="btn btn-outline-primary js-btn-minus btnQuantite" type="button">&minus;</button>
                            </div>
                            <input id="quantiteProduit" type="text" class="form-control text-center border mr-0" value="1" min="1" placeholder=""
                                   aria-label="Example text with button addon" aria-describedby="button-addon1">
                            <div class="input-group-append">
                                <button id="btnQuantitePlus" class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
                            </div>
                        </div>

                    </div>
                    <p><a id="addToCart" href="" class="buy-now btn btn-sm height-auto px-4 py-3 btn-primary">{{ 'addCart' | trans }}</a></p>


                </div>
            </div>
        </div>
    </div>
    <script>
        var quantite = parseInt(document.getElementById("quantiteProduit").value) -1;
        var route = "{{ path('panier_ajouter', { '_locale' : 'fr', 'idProduit' : single.id}) }}/" + (quantite == 0 ? '1' : quantite);
        document.getElementById('addToCart').setAttribute("href", route);

        document.getElementById("btnQuantitePlus").addEventListener("click", function(){
            var quantite = parseInt(document.getElementById("quantiteProduit").value) +1;
            var route = "{{ path('panier_ajouter', { '_locale' : 'fr', 'idProduit' : single.id}) }}/" + quantite;
            document.getElementById('addToCart').setAttribute("href", route);
        });

        document.getElementById("btnQuantiteMinus").addEventListener("click", function(){
            var quantite = parseInt(document.getElementById("quantiteProduit").value) -1;
            var route = "{{ path('panier_ajouter', { '_locale' : 'fr', 'idProduit' : single.id}) }}/" + (quantite == 0 ? '1' : quantite);
            document.getElementById('addToCart').setAttribute("href", route);
        });
    </script>
{% endblock %}

templates/wines.html.twig
{# templates/shop.html.twig #}
{% extends 'base.html.twig' %}
{% block content %}
    <div class="site-section mt-5">

    <div class="container">
        <div class="row categories">
            {% for item in categories %}
                <div class="col-lg-4 mb-5 col-md-6">
                    <div class="wine_v_1 text-center pb-4">
                        <a href="{{ path('product_page', { '_locale' : 'fr', 'categorie' : item.id}) }}" class="thumbnail d-block mb-4"><img src="{{ asset(item.visuel) }}" alt="Image" class="img-categorie"></a>
                        <div>
                            <h3 class="heading mb-1"><a href="#">{{ item.libelle }}</a></h3>
                        </div>


                        <div class="wine-actions">
                            <h3 class="heading-2">Découvrir les produits<a href="#"></a></h3>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}